DefaultContentLanguage = "as"
baseURL = "https://ahilapaati.com/"
theme = "ink"
paginate = 5

copyright = "2020Â©Copyright"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#googleAnalytics = "UA-123-45"

[params]
	subtitle = "Something else."

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page","interview"]

	featherIconsCDN = true

	mode = "light" # "dark" or "auto"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/knadh/ink"


[languages]
  [languages.en]
    languageName = "English"
    langFlag = "ğŸ‡¬ğŸ‡§"
    title = "Ahila Paati, Etyadi."
    weight = 1
	[languages.en.Taxonomies]
   		category = "categories"
  [languages.as]
    languageName = "à¦…à¦¸à¦®à§€à¦¯à¦¼à¦¾"
	title = "à¦†à¦¹à¦¿à¦²à¦¾ à¦ªà¦¾à¦¤à¦¿, à¦‡à¦¤à§à¦¯à¦¾à¦¦à¦¿à¥¤"
    langFlag = "ğŸ‡®ğŸ‡³"
    weight = 2
	[languages.as.Taxonomies]
   		category = "categories"

[[languages.as.menu.main]]
url    = "/"
name   = "à¦—à§ƒà¦¹"
weight = 1

[[languages.as.menu.main]]
url    = "/categories"
name   = "à¦¬à¦¿à¦­à¦¾à¦—"
weight = 2

[[languages.as.menu.main]]
url    = "/about"
name   = "à¦¤à¦¥à§à¦¯"
weight = 3

# Nav.
[[languages.en.menu.main]]
url = "/en/"
name = "Home"
weight = 1

[[languages.en.menu.main]]
name = "Categories"
url = "/en/categories"
weight = 2

[[languages.en.menu.main]]
name = "About"
url = "/en/about"
weight = 3